# Generated by Django 5.1.6 on 2025-03-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='email',
            field=models.EmailField(default='dina@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(default='dina.png', upload_to='trainee/img'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
