# Generated by Django 5.1.6 on 2025-03-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainee_email_trainee_image_alter_trainee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
