# Generated by Django 5.1.6 on 2025-03-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_image'),
        ('trainee', '0003_trainee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='course.course'),
        ),
    ]
