# Generated by Django 5.1.6 on 2025-03-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='dina.png', upload_to='course/img'),
        ),
    ]
